---
- name: Cisco test playbook
  hosts: all

  tasks:
    - name: run show version on the routers
      ios_command:
        commands:
        - show version | incl Version
        - show ip int br
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
